### ISSUE TITLE
using PARALLEL as variable name is a bad choice

### ISSUE THREAD

**Issue by leapfog** [nathanhaigh/parallel-rsync#5]
from man parallel:
```
The environment variable $PARALLEL will be used as default options for GNU parallel.
```

Using a variable with that name in your script breaks both, GNU Parallel and your script
(in case that variable was already defined and exported in the shell running prsync):

 - the default options aren't used anymore (as you replaced them with a number)
 - GNU Parallel inserts it between the options you specify and the rsync command
 
see:
```
$ export PARALLEL="foobar"
$ prsync --dry-run /etc /tmp
[...]
4 rsync --files-from=/tmp/tmp.x5RPF2DlGl/chunk.0 --dry-run /etc /tmp
```
(note the `4` before `rsync`)

**Comment by nathanhaigh** [comment]
Thanks for reporting this issue so clearly @leapfog! Now fixed.
